import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const URL = process.env.POSTER_URL ?? "http://localhost:5174/poster.html";
const OUT = process.env.OUT ?? "/tmp/crop.png";
const [X,Y,W,H] = (process.env.CROP ?? "0,0,900,900").split(",").map(Number);
const b = await puppeteer.launch({ executablePath: CHROME, headless: "new", args:["--force-color-profile=srgb"] });
const p = await b.newPage();
await p.setViewport({ width: 1900, height: 1500, deviceScaleFactor: 2 });
await p.goto(URL, { waitUntil: "networkidle0" });
await p.evaluateHandle("document.fonts.ready");
const el = await p.$(".poster");
const box = await el.boundingBox();
await p.screenshot({ path: OUT, clip: { x: box.x + X, y: box.y + Y, width: W, height: H } });
await b.close();
console.log("cropped", OUT, "from poster", Math.round(box.width)+"x"+Math.round(box.height));
